### ISSUE TITLE
Qr Code Downloading & Qr Code saving page

### ISSUE THREAD

**Issue by joshman58** [zuri-training/Project-QR-Gen-Team-52-Frontend#7]

**Comment by joshman58** [comment]
Please add a link to your work

**Comment by solo-blaze** [comment]
https://www.figma.com/file/1g4hAgOiGRBuPEJGPnRWKj/Zuri-Team-52-(Qr-generator)?node-id=1%3A4 

inspiration was gotten from other designs across various platform and i tried my possible best to make the design user friendly so that the users will be able to carry out their task perfectly without wasting time

also the element use for the design were all gotten from the style guide which was created
